{
 "title": "Geth Compatible Chains: Ethereum, BSC, Arbitrum, Polygon, Linea, Ankara (Prometheus)",
 "description": "A dashboard compatible with geth built in Prometheus metrics, found with chains as Ethereum, BSC, Arbitrum.",
 "tags": [
  "Blockchain",
  "Geth",
  "Ethereum",
  "Arbitrum",
  "Nitro"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   { "name": "job", "query": { "query": "label_values(job)" } },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPC Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current RPC Requests Per Minute",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(rpc_requests{job=\"$job\", juju_model=\"$juju_model\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RPC Requests",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_requests{job=\"$job\", juju_model=\"$juju_model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "increase(rpc_requests{job=\"$job\", juju_model=\"$juju_model\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "increase(rpc_requests{job=\"$job\", juju_model=\"$juju_model\"}[1m])/60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current RPC Requests Per Second",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(rpc_requests{job=\"$job\", juju_model=\"$juju_model\"}[1m])/60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Main",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{job=\"$job\", juju_model=\"$juju_model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Rate (tx/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(txpool_known{job=\"$job\", juju_model=\"$juju_model\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "txpool_pending{job=\"$job\", juju_model=\"$juju_model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total System Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\", juju_model=\"$juju_model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Geth CPU Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_threads{job=\"$job\", juju_model=\"$juju_model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Received Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{job=\"$job\", juju_model=\"$juju_model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Geth Processor Loading",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_cpu_procload{job=\"$job\", juju_model=\"$juju_model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Geth Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_used{job=\"$job\", juju_model=\"$juju_model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peers{job=\"$job\", juju_model=\"$juju_model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "p2p_peers{job=\"$job\", juju_model=\"$juju_model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic (bytes/s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(p2p_egress{job=\"$job\", juju_model=\"$juju_model\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(p2p_ingress{job=\"$job\", juju_model=\"$juju_model\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Network p2p (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(p2p_egress{job=\"$job\", juju_model=\"$juju_model\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Network p2p (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(p2p_egress{job=\"$job\", juju_model=\"$juju_model\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Activity (bytes/s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{job=\"$job\", juju_model=\"$juju_model\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(system_disk_writebytes{job=\"$job\", juju_model=\"$juju_model\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read Activity (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{job=\"$job\", juju_model=\"$juju_model\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write Activity (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(system_disk_writebytes{job=\"$job\", juju_model=\"$juju_model\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain Data Disk Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_size{job=\"$job\", juju_model=\"$juju_model\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}