{
 "title": "ZFS Utilization 2",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{nodename=\"$hostname\"},instance)"
    }
   },
   { "name": "pool_name", "label": "Pool", "query": { "query": "label_values(pool)" } },
   { "name": "hostname", "label": "Hostname", "query": { "query": "label_values(nodename)" } }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity (zpool: default)",
     "type": "timeseries",
     "description": "Space available on selected pools",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "zfs_dataset_available_bytes{instance=\"$instance:9134\",job=\"prometheus-zfs-exporter\",pool=\"$pool_name\", name=\"$pool_name\"}",
       "legendFormat": "available"
      },
      {
       "expr": "zfs_dataset_used_bytes{instance=\"$instance:9134\",job=\"prometheus-zfs-exporter\",pool=\"$pool_name\", name=\"$pool_name\"}",
       "legendFormat": "used"
      },
      {
       "expr": "zfs_pool_size_bytes{instance=\"$instance:9134\",job=\"prometheus-zfs-exporter\",pool=\"$pool_name\"}",
       "legendFormat": "size"
      }
     ]
    },
    {
     "title": "Allocated disk in pool",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((zfs_pool_allocated_bytes{instance=\"$instance:9134\",pool=\"$pool_name\"} * 100) / zfs_pool_size_bytes{instance=\"$instance:9134\",job=\"prometheus-zfs-exporter\", pool=\"$pool_name\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Total Dataset disk usage at $instance in $pool_name pool",
     "type": "timeseries",
     "description": "This shows a total summary of all datasets used disk space on a specific host and pool.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "zfs_dataset_used_bytes{instance=\"$instance:9134\", name=\"$pool_name/containers\", pool=\"$pool_name\"}",
       "legendFormat": "{{instance}} - {{pool}}"
      }
     ]
    },
    {
     "title": "zfs_pool_health",
     "type": "stat",
     "description": "[ONLINE]\n    The device or virtual device is in normal working order. Although some transient errors might still occur, the device is otherwise in working order.\n\n[DEGRADED]\n    The virtual device has experienced a failure but can still function. This state is most common when a mirror or RAID-Z device has lost one or more constituent devices. The fault tolerance of the pool might be compromised, as a subsequent fault in another device might be unrecoverable.\n\n[FAULTED]\n    The device or virtual device is completely inaccessible. This status typically indicates total failure of the device, such that ZFS is incapable of sending data to it or receiving data from it. If a top-level virtual device is in this state, then the pool is completely inaccessible.\n\n[OFFLINE]\n    The device has been explicitly taken offline by the administrator.\n\n[UNAVAIL]\n    The device or virtual device cannot be opened. In some cases, pools with UNAVAIL devices appear in DEGRADED mode. If a top-level virtual device is UNAVAIL, then nothing in the pool can be accessed.\n\n[REMOVED]\n    The device was physically removed while the system was running. Device removal detection is hardware-dependent and might not be supported on all platforms.",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zfs_pool_health{instance=\"$instance:9134\",job=\"prometheus-zfs-exporter\",pool=\"$pool_name\"}",
       "legendFormat": "pool: {{pool}}"
      }
     ]
    },
    {
     "title": "Days until fillup percentage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zfs_dataset_available_bytes{instance=\"$instance:9134\",job=\"prometheus-zfs-exporter\",pool=\"$pool_name\", name=\"$pool_name\"}/abs(delta(zfs_dataset_available_bytes{instance=\"$instance:9134\",job=\"prometheus-zfs-exporter\",pool=\"$pool_name\", name=\"$pool_name\"}[1d]) < 0)",
       "legendFormat": "100%"
      },
      {
       "expr": "zfs_dataset_available_bytes{instance=\"$instance:9134\",job=\"prometheus-zfs-exporter\",pool=\"$pool_name\", name=\"$pool_name\"}/abs(delta(zfs_dataset_available_bytes{instance=\"$instance:9134\",job=\"prometheus-zfs-exporter\",pool=\"$pool_name\", name=\"$pool_name\"}[1d]) < 0) * 0.95",
       "legendFormat": "95%"
      },
      {
       "expr": "zfs_dataset_available_bytes{instance=\"$instance:9134\",job=\"prometheus-zfs-exporter\",pool=\"$pool_name\", name=\"$pool_name\"}/abs(delta(zfs_dataset_available_bytes{instance=\"$instance:9134\",job=\"prometheus-zfs-exporter\",pool=\"$pool_name\", name=\"$pool_name\"}[1d]) < 0) * 0.9",
       "legendFormat": "90%"
      }
     ]
    },
    {
     "title": "TOP 10 Datasets used delta the past 2h",
     "type": "piechart",
     "description": "This shows memory used delta of all datasets over the past 2h on all hosts and $pool_name pool.",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, delta(zfs_dataset_used_bytes{name=~\"$pool_name/containers/.*\", pool=\"$pool_name\"}[2h]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "TOP 5 Datasets with the highest write rate last 4h",
     "type": "piechart",
     "description": "This shows the top 5 container with the highest write rate in past 4 hours on all hosts and $pool_name pool.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, rate(zfs_dataset_written_bytes{name=~\"$pool_name/containers/.*\", pool=\"$pool_name\", type=\"filesystem\"}[4h]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "TOP 5 Datasets with most used disk rate last 24h",
     "type": "piechart",
     "description": "This shows the top 5 datasets with the most used data rate in past 24 hours on all hosts and $pool_name pool.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, rate(zfs_dataset_used_bytes{name=~\"$pool_name/containers/.*\", pool=\"$pool_name\", type=\"filesystem\"}[24h]))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ZFS Datasets on $hostname that use $pool_name pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "TOP 10 containers with most used disk on $hostname",
   "type": "piechart",
   "description": "This shows the top 10 datasets with the most used disk on $hostname and pool $pool_name.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, zfs_dataset_used_bytes{instance=\"$instance:9134\", name=~\"$pool_name/containers/.*\", pool=\"$pool_name\", type=\"filesystem\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Datasets used delta the past 2h",
   "type": "timeseries",
   "description": "This shows the delta of used memory by all datasets over the past 2h on a specific host and pool.",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(zfs_dataset_used_bytes{instance=\"$instance:9134\", name=~\"$pool_name/containers/.*\", pool=\"$pool_name\"}[2h])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "TOP 5 with the highest write rate last 4h",
   "type": "piechart",
   "description": "This shows the top 5 datasets with the highest write rate in past 4 hours on a specific host and pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, rate(zfs_dataset_written_bytes{instance=\"$instance:9134\", name=~\"$pool_name/containers/.*\", pool=\"$pool_name\", type=\"filesystem\"}[4h]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "TOP 5 with most used disk rate last 24h",
   "type": "piechart",
   "description": "This shows the top 5 datasets with the most used data rate in past 24 hours on a specific host and pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, rate(zfs_dataset_used_bytes{instance=\"$instance:9134\", name=~\"$pool_name/containers/.*\", pool=\"$pool_name\", type=\"filesystem\"}[24h]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk usage statistics of $hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=\"$instance:9100\",job=\"prometheus-node-exporter\"}[5m])/irate(node_disk_reads_completed_total{instance=\"$instance:9100\",job=\"prometheus-node-exporter\"}[5m]) * 100",
     "legendFormat": "{{device}} sec-per-Read-completed"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=\"$instance:9100\",job=\"prometheus-node-exporter\"}[5m])/irate(node_disk_writes_completed_total{instance=\"$instance:9100\",job=\"prometheus-node-exporter\"}[5m]) * 100",
     "legendFormat": "{{device}} sec-per-Write-completed"
    }
   ]
  },
  {
   "title": "ARC size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_arc_size{instance=\"$instance:9100\", job=\"prometheus-node-exporter\"}",
     "legendFormat": "ARC Free"
    }
   ]
  },
  {
   "title": "Process schedule stats Running / Waiting",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_schedstat_running_seconds_total{instance=\"$instance:9100\",job=\"prometheus-node-exporter\"}[5m])",
     "legendFormat": "CPU {{cpu}} - seconds spent by this CPU running a process"
    },
    {
     "expr": "irate(node_schedstat_waiting_seconds_total{instance=\"$instance:9100\",job=\"prometheus-node-exporter\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$instance:9100\",job=\"prometheus-node-exporter\"}[5m])",
     "legendFormat": "{{device}}-Reads Completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$instance:9100\",job=\"prometheus-node-exporter\"}[5m])",
     "legendFormat": "{{device}}-writes Completed"
    }
   ]
  }
 ]
}